-- Path of Building
--
-- Knowledge: league 3.29 meta momentum
-- Curated from the official 3.29 patch notes, reviewed by the domain expert
-- on 2026-08-13 with cross-checks against the day 3 poe.ninja ladder.
-- 0.5 means untouched by the patch, above means buffed, below means nerfed.
-- Unlisted gems receive defaultMomentum. Only verified numbers may be used
-- as sources; see the curation workflow and rubric in knowledge/README.md.
--

return {
	league = "3.29",
	defaultMomentum = 0.5,
	skills = {
		-- kept from the reviewed file, unchanged (change list evidence agrees)
		["Winter Orb"] = { momentum = 0.90, note = "projectiles 1 to 2-3, crit 6 to 7.5, 25 percent freeze" },
		["Fireball"] = { momentum = 0.70, note = "added damage effectiveness 370 to 480 at gem 20" },
		["Crackling Lance"] = { momentum = 0.70, note = "cast time 0.65 to 0.5, mana cost up 25 percent" },
		["Divine Ire"] = { momentum = 0.65, note = "steeper damage growth past gem 20" },
		["Hexblast"] = { momentum = 0.65, note = "cooldown 2 to 1 seconds, cast 1 to 0.85" },
		["Elemental Hit"] = { momentum = 0.35, note = "added elemental damage lowered 17 percent" },
		["Kinetic Blast"] = { momentum = 0.40, note = "Arcane Might 200 to 150, area damage penalty up" },

		-- new entries from the 3.29 change list
		["Arcane Cloak"] = { momentum = 0.35, note = "buff grants 10 percent flat lightning from mana spent, was 10-14; judgment: nerf at high levels" },
		["Absolution"] = { momentum = 0.70, note = "cast time 0.75 to 0.65s" },
		["Absolution of Inspiring"] = { momentum = 0.70, note = "cast time 0.75 to 0.65s" },
		["Arc"] = { momentum = 0.60, note = "cast time 0.7 to 0.6s, mana cost up 25 percent" },
		["Arc of Oscillating"] = { momentum = 0.60, note = "cast time 0.7 to 0.6s, mana cost up 25 percent" },
		["Arc of Surging"] = { momentum = 0.85, note = "beam splits to 6-9 targets was 4-7, cast time 0.7 to 0.6s" },
		["Armageddon Brand of Volatility"] = { momentum = 0.80, note = "damage effectiveness 370 to 520 percent at gem 20" },
		["Barrage"] = { momentum = 0.90, note = "fires 6 projectiles, up from 5" },
		["Ball Lightning"] = { momentum = 0.65, note = "radius 1.8 to 2m, cast 0.7 to 0.6s, mana up 25 percent" },
		["Ball Lightning of Orbiting"] = { momentum = 0.60, note = "cast time 0.6 to 0.5s, mana cost up 25 percent" },
		["Ball Lightning of Static"] = { momentum = 0.65, note = "cast 0.7 to 0.6s, mana up 25 percent, 4 cooldown uses was 3" },
		["Blade Blast"] = { momentum = 0.75, note = "radius 1.4 to 1.5m, crit chance 6 to 10 percent" },
		["Blade Blast of Dagger Detonation"] = { momentum = 0.75, note = "radius 2.6 to 2.8m, crit chance 6 to 10 percent" },
		["Blade Blast of Unloading"] = { momentum = 0.70, note = "more AoE per blade detonated 80 to 100 percent, crit 10 percent" },
		["Blade Vortex"] = { momentum = 0.35, note = "hit rate and per-blade damage cut 35 to 30 percent, crit up to 10; judgment: scaling cut outweighs crit gain" },
		["Blade Vortex of the Scythe"] = { momentum = 0.60, note = "crit chance 6 to 10 percent, damage effectiveness 370 percent at gem 20" },
		["Bladefall"] = { momentum = 0.70, note = "damage effectiveness 140 to 160 percent at gem 20" },
		["Bladefall of Impaling"] = { momentum = 0.75, note = "crit chance 15 to 25 percent, damage effectiveness up to 170 percent" },
		["Bladefall of Trarthus"] = { momentum = 0.65, note = "damage effectiveness 120 to 140 percent at gem 20" },
		["Bladefall of Volleys"] = { momentum = 0.65, note = "damage effectiveness 100 to 120 percent at gem 20" },
		["Blazing Salvo"] = { momentum = 0.70, note = "damage effectiveness 60 to 70 percent, mana cost down 20 percent" },
		["Blight"] = { momentum = 0.65, note = "radius plus 0.2m, base CPS 421.5 to 469 at gem 20" },
		["Blight of Atrophy"] = { momentum = 0.55, note = "plus 0.2m to base radius at all levels" },
		["Blight of Contagion"] = { momentum = 0.65, note = "radius plus 0.2m, base chaos damage per second up to 950.5" },
		["Bodyswap"] = { momentum = 0.80, note = "fire damage 4 to 6 percent max life, AoE 200 to 300 percent more, cast down" },
		["Bodyswap of Sacrifice"] = { momentum = 0.70, note = "AoE 200 to 300 percent more if consuming minion, cast time 0.65s" },
		["Cold Snap"] = { momentum = 0.85, note = "new 25 percent freeze chance, crit and cast improved, CPS 2260 to 2736" },
		["Cold Snap of Power"] = { momentum = 0.75, note = "new 25 percent freeze, power charge chance on crit 30 to 50 percent" },
		["Contagion"] = { momentum = 0.70, note = "radius scales to 2.1m, base CPS 281.5 to 336.5 at gem 20" },
		["Contagion of Subsiding"] = { momentum = 0.60, note = "radius scales 1.7 to 2.1m, up from flat 1.7m" },
		["Contagion of Transference"] = { momentum = 0.60, note = "radius scales 2 to 2.4m, up from flat 2m" },
		["Corrupting Fever"] = { momentum = 0.80, note = "debuff duration 1 to 1.5s, base DPS 335.4 to 411.7 at gem 20" },
		["Crackling Lance of Branching"] = { momentum = 0.65, note = "damage effectiveness 330 to 370 percent at gem 20" },
		["Crackling Lance of Disintegration"] = { momentum = 0.65, note = "damage effectiveness 360 to 400 percent at gem 20" },
		["Creeping Frost"] = { momentum = 0.35, note = "damage effectiveness cut 130 to 90 percent at gem 20; judgment: net nerf despite crit/CPS gains" },
		["Creeping Frost of Floes"] = { momentum = 0.30, note = "hit damage cut 395-592 to 248-372, damage effectiveness 80 to 65 percent; judgment: net nerf" },
		["Cremation"] = { momentum = 0.55, note = "quality now grants 0-15 percent faster projectiles, was 0-10" },
		["Cremation of Exhuming"] = { momentum = 0.55, note = "fires every 0.8s was 1s but 3 projectiles was 4, quality improved" },
		["Cremation of the Volcano"] = { momentum = 0.60, note = "duration 2.5 to 2s but max geysers 6 to 8, quality now plus max geysers" },
		["Dark Bargain"] = { momentum = 0.65, note = "crit chance 7 to 10 percent" },
		["Dark Bargain of Trarthus"] = { momentum = 0.70, note = "sacrifice deals 600 percent of life as chaos was 500, crit 7 to 10" },
		["Discharge"] = { momentum = 0.80, note = "cooldown 2 to 1s, 15 percent higher base damage per charge removed" },
		["Discharge of Misery"] = { momentum = 0.65, note = "15 percent higher base damage per charge removed at all levels" },
		["Divine Blast"] = { momentum = 0.60, note = "off-hand physical damage up about 9 percent at all levels" },
		["Divine Ire of Disintegration"] = { momentum = 0.60, note = "damage effectiveness 130 to 140 percent at gem 20" },
		["Divine Ire of Holy Lightning"] = { momentum = 0.75, note = "damage effectiveness 65 to 100 percent at gem 20" },
		["Divine Retribution"] = { momentum = 0.80, note = "cooldown 5 to 4s, damage effectiveness 390 to 540 percent at gem 20" },
		["Energy Blade"] = { momentum = 0.35, note = "now requires all equipped weapons to be swords; judgment: build restriction, real nerf" },
		["Essence Drain"] = { momentum = 0.55, note = "base CPS 2170 to 2729 at gem 20 but hit damage cut; judgment: CPS gain likely nets positive for a DoT" },
		["Essence Drain of Wickedness"] = { momentum = 0.85, note = "now fires 3-5 projectiles, up from 1 at all levels" },
		["Essence Drain of Desperation"] = { momentum = 0.60, note = "chaos DPS 4726.1 to 5321.8 at gem 20" },
		["Ethereal Knives"] = { momentum = 0.80, note = "projectiles 10-13 to 10-15, crit 6 to 10, damage effectiveness 220 to 250" },
		["Ethereal Knives of Lingering Blades"] = { momentum = 0.80, note = "projectiles 6-8 to 7-10, crit 6 to 10, damage effectiveness 220 to 250" },
		["Ethereal Knives of the Massacre"] = { momentum = 0.60, note = "crit chance 6 to 10 percent" },
		["Exsanguinate"] = { momentum = 0.70, note = "base DPS 1534.2 to 1905.5 at gem 20" },
		["Exsanguinate of Transmission"] = { momentum = 0.70, note = "base physical DPS 1718.9 to 2134.9 at gem 20" },
		["Eye of Winter"] = { momentum = 0.55, note = "crit chance 6 to 7.5 percent" },
		["Eye of Winter of Finality"] = { momentum = 0.55, note = "crit chance 6 to 7.5 percent" },
		["Eye of Winter of Transience"] = { momentum = 0.55, note = "crit chance 6 to 7.5 percent" },
		["Firestorm"] = { momentum = 0.70, note = "damage effectiveness 80 to 100 percent, mana cost down 20 percent" },
		["Firestorm of Meteors"] = { momentum = 0.75, note = "radius 2.3 to 2.6m, mana down 20 percent, damage effectiveness 410 to 520" },
		["Firestorm of Pelting"] = { momentum = 0.70, note = "damage effectiveness 120 to 150 percent, mana cost down 20 percent" },
		["Flame Dash"] = { momentum = 0.65, note = "damage effectiveness 140 to 170 percent, base DPS 1738.6 to 1999.3" },
		["Flame Dash of Return"] = { momentum = 0.75, note = "damage effectiveness 340 to 430 percent, mana cost down 20 percent" },
		["Flame Surge"] = { momentum = 0.80, note = "damage effectiveness 190 to 270 percent, burning ground 25 to 30, mana down 20" },
		["Flame Surge of Combusting"] = { momentum = 0.75, note = "damage effectiveness 310 to 410 percent, mana cost down 20 percent" },
		["Flame Wall"] = { momentum = 0.65, note = "base DPS 679.9 to 778.7, secondary DPS up, quality now plus 2 max walls" },
		["Flameblast"] = { momentum = 0.75, note = "radius per stage 0.3 to 0.4m, damage effectiveness 90 to 120, mana down 20" },
		["Flameblast of Celerity"] = { momentum = 0.80, note = "radius 0.8 to 1m, mana cost down 20 percent, damage effectiveness 100 to 140" },
		["Flameblast of Contraction"] = { momentum = 0.70, note = "radius 2.6 to 3.0m, mana cost down 20 percent, damage effectiveness 30 to 40" },
		["Forbidden Rite"] = { momentum = 0.65, note = "chaos damage 12 to 14 percent of maximum life" },
		["Freezing Pulse"] = { momentum = 0.85, note = "projectiles 1 to 1-5 across levels, crit 6 to 7.5, damage effectiveness up" },
		["Frost Bomb"] = { momentum = 0.80, note = "new 25 percent freeze chance, damage effectiveness 310 to 380 percent" },
		["Frost Bomb of Forthcoming"] = { momentum = 0.70, note = "damage effectiveness 370 to 460 percent, duration cut to 2s; judgment: damage gain outweighs shorter duration" },
		["Frost Bomb of Instability"] = { momentum = 0.75, note = "new 25 percent freeze chance, damage effectiveness 260 to 330 percent" },
		["Frostblink"] = { momentum = 0.65, note = "crit chance 5 to 7.5 percent" },
		["Frostblink of Wintry Blast"] = { momentum = 0.65, note = "crit chance 5 to 7.5 percent" },
		["Frostbolt"] = { momentum = 0.75, note = "new 25 percent freeze chance, crit chance 5 to 7.5 percent" },
		["Galvanic Field"] = { momentum = 0.80, note = "shock chance 20 to 50 percent, damage effectiveness 100 to 130, mana up 25" },
		["Galvanic Field of Intensity"] = { momentum = 0.80, note = "shock chance 20 to 50 percent, damage effectiveness 350 to 470, mana up 25" },
		["General's Cry"] = { momentum = 0.30, note = "support effect can no longer support skills with cooldowns; judgment: real build restriction" },
		["Glacial Cascade"] = { momentum = 0.65, note = "crit chance 5 to 6 percent, damage effectiveness 65 to 75 percent at gem 20" },
		["Hexblast of Contradiction"] = { momentum = 0.80, note = "cooldown 2 to 1s, cast time 1 to 0.85s, mana cost down 15 percent" },
		["Hexblast of Havoc"] = { momentum = 0.70, note = "radius 2.5 to 2.8m, crit chance 6 to 10 percent" },
		["Holy Flame Totem"] = { momentum = 0.55, note = "crit chance 5 to 6 percent" },
		["Holy Flame Totem of Ire"] = { momentum = 0.55, note = "crit chance 5 to 6 percent" },
		["Holy Hammers"] = { momentum = 0.55, note = "base radius now flat 1.8m, up from 1.6-1.8m scaling" },
		["Hydrosphere"] = { momentum = 0.55, note = "crit chance 5 to 6 percent" },
		["Ice Nova"] = { momentum = 0.70, note = "new 25 percent freeze chance, damage effectiveness 230 to 250 percent" },
		["Ice Nova of Deep Freeze"] = { momentum = 0.85, note = "now always freezes, was 50 percent chance; damage effectiveness 140 to 180" },
		["Ice Nova of Frostbolts"] = { momentum = 0.60, note = "new 25 percent freeze chance, crit chance 6 to 7.5 percent" },
		["Ice Spear"] = { momentum = 0.55, note = "crit chance 7 to 7.5 percent" },
		["Ice Spear of Splitting"] = { momentum = 0.75, note = "crit 5 to 7.5 percent, splits to 4-7 targets, was 2-5" },
		["Incinerate"] = { momentum = 0.85, note = "max stages 8 to 10, damage effectiveness 50 to 70 percent, cast time down" },
		["Incinerate of Expanse"] = { momentum = 0.70, note = "damage effectiveness 50 to 70 percent at gem 20" },
		["Incinerate of Venting"] = { momentum = 0.65, note = "damage effectiveness 55 to 70 percent at gem 20" },
		["Kinetic Blast of Clustering"] = { momentum = 0.40, note = "Arcane Might 200 to 150 percent, added physical damage now 10-15 of max mana" },
		["Kinetic Fusillade"] = { momentum = 0.40, note = "attack speed 200 to 125 percent, duration 0.7 to 0.5s, mana cost up; judgment: nerfed but remains strong, expert read plus day 3 play 2 percent" },
		["Kinetic Rain"] = { momentum = 0.65, note = "Arcane Might 150 to 200 percent" },
		["Kinetic Rain of Impact"] = { momentum = 0.65, note = "Arcane Might 150 to 200 percent" },
		["Lightning Conduit"] = { momentum = 0.65, note = "damage effectiveness 140 to 170 percent at gem 20, mana cost up 25 percent" },
		["Lightning Conduit of the Heavens"] = { momentum = 0.85, note = "hits up to 8-15 enemies was 6-12, shocks as though dealing 200 more damage" },
		["Lightning Tendrils"] = { momentum = 0.80, note = "damage effectiveness 130 to 190 percent, cast time down, mana cost up 25" },
		["Lightning Tendrils of Eccentricity"] = { momentum = 0.70, note = "damage effectiveness 60 to 85 percent at gem 20" },
		["Lightning Tendrils of Escalation"] = { momentum = 0.70, note = "damage effectiveness 260 to 370 percent at gem 20" },
		["Lightning Warp"] = { momentum = 0.60, note = "cast time 0.7 to 0.6s, mana cost up 25 percent, crit 5 to 6 percent" },
		["Manabond"] = { momentum = 0.75, note = "cast time 0.8 to 0.6s" },
		["Orb of Storms"] = { momentum = 0.60, note = "cast time 0.5 to 0.4s, mana cost up 25 percent" },
		["Orb of Storms of Squalls"] = { momentum = 0.70, note = "damage effectiveness 140 to 190 percent at gem 20" },
		["Purifying Flame"] = { momentum = 0.70, note = "radius quality bonus doubled, crit up, damage effectiveness 300 to 350" },
		["Purifying Flame of Revelations"] = { momentum = 0.60, note = "crit chance 5.5 to 6 percent, damage effectiveness 230 percent at gem 20" },
		["Quickstep"] = { momentum = 0.60, note = "now able to dash over terrain" },
		["Reap"] = { momentum = 0.70, note = "base DPS 2002.5 to 2422.5 at gem 20" },
		["Rolling Magma"] = { momentum = 0.65, note = "damage effectiveness 280 to 320 percent, mana cost down 20 percent" },
		["Scorching Ray"] = { momentum = 0.70, note = "cast time down, base DPS 780.7 to 914 at gem 20" },
		["Scorching Ray of Immolation"] = { momentum = 0.70, note = "base duration 3 to 4s, base fire damage per second up to 2744" },
		["Searing Bond"] = { momentum = 0.80, note = "plus 2 max summoned totems was plus 1, base DPS 3899.6 to 4430.6" },
		["Searing Bond of Detonation"] = { momentum = 0.55, note = "radius scales 2.3 to 2.7m at gem 1-20, up from 2 to 2.4m" },
		["Shock Nova"] = { momentum = 0.65, note = "cast time 0.7 to 0.6s, damage effectiveness 190 to 220, mana up 25 percent" },
		["Shock Nova of Procession"] = { momentum = 0.45, note = "damage range widened 263-790 to 105-948, same average; mana cost up 25 percent" },
		["Siphoning Trap of Pain"] = { momentum = 0.75, note = "hits 13-18 enemies was 11-15, base CPS 2546.9 to 3085.7 at gem 20" },
		["Somatic Shell"] = { momentum = 0.85, note = "damage 20-50 to 35-60 percent, attack speed 100 to 115, radius 1.5 to 1.8m" },
		["Soulrend"] = { momentum = 0.75, note = "cast time 0.8 to 0.7s, base CPS 3149.4 to 3840.8, mana down 15 percent" },
		["Soulrend of Reaping"] = { momentum = 0.85, note = "now fires 3-5 projectiles was 1 flat, crit chance 10 percent" },
		["Spark"] = { momentum = 0.60, note = "cast time 0.65 to 0.6s, mana cost up 25 percent" },
		["Spark of the Nova"] = { momentum = 0.35, note = "projectiles cut to 6-10, was 8-12; cast time 0.7s" },
		["Spark of Unpredictability"] = { momentum = 0.65, note = "projectiles 3-6 to 4-7, cast time 0.6s" },
		["Storm Burst"] = { momentum = 0.65, note = "damage effectiveness 35 to 45 percent at gem 20" },
		["Storm Burst of Repulsion"] = { momentum = 0.60, note = "damage effectiveness 70 to 80 percent at gem 20" },
		["Storm Call"] = { momentum = 0.65, note = "cast time 0.5 to 0.4s, damage effectiveness 250 to 270, mana up 25 percent" },
		["Stormbind"] = { momentum = 0.65, note = "damage effectiveness 160 to 200 percent at gem 20, mana cost up 25 percent" },
		["Stormbind of Teleportation"] = { momentum = 0.65, note = "damage effectiveness 160 to 200 percent at gem 20" },
		["Tornado of Elemental Turbulence"] = { momentum = 0.65, note = "damage effectiveness 65 to 80 percent at gem 20" },
		["Unearth"] = { momentum = 0.65, note = "crit chance 6 to 10 percent" },
		["Void Sphere"] = { momentum = 0.75, note = "conversion 40 to 60 percent chaos, damage effectiveness 75 to 100 percent" },
		["Void Sphere of Rending"] = { momentum = 0.60, note = "radius 2.4 to 2.8m, crit chance 5 to 7 percent" },
		["Volatile Dead of Confinement"] = { momentum = 0.55, note = "base explosion radius 2 to 2.3m" },
		["Voltaxic Burst"] = { momentum = 0.75, note = "crit 5.5 to 10 percent, conversion 40 to 60 chaos, more corpse life consumed" },
		["Vortex"] = { momentum = 0.85, note = "cast time 0.75 to 0.6s, new 25 percent freeze, base CPS 2772.8 to 3245.7" },
		["Vortex of Projection"] = { momentum = 0.65, note = "cast time 0.75 to 0.6s, crit chance 6 to 7.5 percent" },
		["Wave of Conviction"] = { momentum = 0.60, note = "cast time 0.7 to 0.6s, mana cost up 15 percent" },
		["Wave of Conviction of Trarthus"] = { momentum = 0.60, note = "cast time 0.7 to 0.6s, mana cost up 15 percent" },
		["Wintertide Brand"] = { momentum = 0.75, note = "base duration 1 to 2s, base CPS 298.5 to 389.8 at gem 20" },

		-- Vaal skill gems
		["Vaal Blade Vortex"] = { momentum = 0.65, note = "crit chance 6 to 10 percent" },
		["Vaal Blight"] = { momentum = 0.85, note = "stores 2 uses was 1, souls per use down, DPS 778.8 to 962.5 at gem 20" },
		["Vaal Cold Snap"] = { momentum = 0.75, note = "stores 2 uses was 1, souls per use 35 to 25, enhanced cold damage output" },
		["Vaal Fireball"] = { momentum = 0.65, note = "radius 0.9-1.4 to 1-1.8m, increased crit chance and damage effectiveness" },
		["Vaal Firestorm"] = { momentum = 0.80, note = "radius 1.3 to 1.8m, burning ground 4 to 6s, damage effectiveness 760 to 920" },
		["Vaal Flameblast"] = { momentum = 0.75, note = "damage effectiveness 60 to 90 percent at gem 20" },
		["Vaal Ice Nova"] = { momentum = 0.85, note = "damage effectiveness 120 to 180, new 25 percent freeze, less AoE shrink per repeat" },
		["Vaal Reap"] = { momentum = 0.85, note = "stores 2 uses was 1, base physical DPS 3881.5 to 4950.3 at gem 20" },
		["Vaal Spark"] = { momentum = 0.80, note = "duration 2 to 3s, damage effectiveness 40 to 60 percent, cast time down" },
		["Vaal Storm Call"] = { momentum = 0.70, note = "cast time 0.5 to 0.4s" },

		-- benchmark main skills with no entry in the 3.29 change list
		["Animate Weapon of Ranged Arms"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Bane of Condemnation"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Boneshatter of Complex Trauma"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Crushing Fist"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Cyclone"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Earthquake"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Earthshatter"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Elemental Hit of the Spectrum"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Elemental Weakness"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Eviscerate"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Explosive Arrow"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Flicker Strike"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Frost Blades"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Ground Slam of Earthshaking"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Ice Crash"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Ice Shot of Penetration"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Ice Trap of Hollowness"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Leap Slam"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Lightning Arrow"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Penance Brand"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Poisonous Concoction of Bouncing"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Raise Spectre"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Raise Zombie"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Smite"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Smite of Divine Judgement"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Spectral Throw"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Splitting Steel"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Static Strike"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Storm Brand of Indecision"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Storm Rain"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Summon Raging Spirit"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Sunder"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
		["Viper Strike of the Mamba"] = { momentum = 0.50, note = "untouched, verified against 3.29 patch notes" },
	},
	supports = {
		-- kept from the reviewed file, unchanged (change list evidence agrees)
		["Spell Totem"] = { momentum = 0.30, note = "55-50 percent less, was 49-40" },
		["Ballista Totem"] = { momentum = 0.35, note = "36-30 percent less, was 32-24" },
		["Barrage Support"] = { momentum = 0.75, note = "50-44 percent less, was 68-62, one more projectile" },

		-- new entries from the 3.29 change list (display names drop the Support
		-- suffix in PoB except Barrage Support, per knowledge/README.md)
		["Archmage"] = { momentum = 0.30, note = "lightning from unreserved mana 10-16 to 8-14 percent; judgment: core scaling nerf hits hard" },
		["Blastchain Mine"] = { momentum = 0.30, note = "deals 60-55 percent less damage was 58-53, cost multiplier 50 to 65 percent" },
		["Cast on Ward Break"] = { momentum = 0.35, note = "cooldown recovery per ward now capped at 400 percent, was uncapped" },
		["Cast while Channelling"] = { momentum = 0.75, note = "triggers every 0.4-0.32s was 0.45-0.35s, triggered less damage 20 was 30" },
		["Charged Mines"] = { momentum = 0.30, note = "throwing speed and crit bonus per charge cut, cost multiplier 120 to 140" },
		["Companionship"] = { momentum = 0.25, note = "no longer grants more max life if only minion, now less damage taken instead; judgment: removes key minion scaling" },
		["Frigid Bond"] = { momentum = 0.75, note = "chill linger duration 2 to 3s, base cold DPS 3566.4 to 4335.8 at gem 20" },
		["High-Impact Mine"] = { momentum = 0.30, note = "deals 60-55 percent less damage was 56-50, cost multiplier 50 to 65 percent" },
		["Infernal Legion"] = { momentum = 0.70, note = "burning radius plus 0.4m, base fire damage per second 2096.6 to 2486.6" },
		["Communion"] = { momentum = 0.15, note = "reworked from Minion Pact into a permanent-minion damage support, cost multiplier up" },
		["Unleash"] = { momentum = 0.65, note = "reoccurring less damage 45-36 to 45-26 percent at gem 1-20, improved scaling" },
		["Greater Unleash"] = { momentum = 0.75, note = "reoccurring less damage 35-31 to 25-23 percent at gem 1-3, large penalty cut" },
	},
}
